version: "3.8"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        environment:
            - PGUSER=postgres
            - PGPASSWORD=H2XyzCTjdNbf9NVWGwYx
            - PGHOST=containers-us-west-175.railway.app
            - PGPORT=7892
            - PGDATABASE=railway
